language: node_js

node_js:
  "8.10.0"

services:
  - postgres


script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov


sudo: required


install:
  - npm install 
  - npm install istanbul
  - npm install -g codecov

notifications: 
  email:
    on_success: never
    on_failure: change