language: node_js
node_js:
  "8.10.0"
script:
  "npm test"
services:
 -postgresql

env:
  -NODE_ENV="development"

install:
  - npm install -g codecov
  - npm install -g nyc

notifications: 
  email:
    on_success: never
    on_failure: change