language: node_js
node_js:
  "8.10.0"

postgres:
  adapter: postgresql
  database: serverMonitorTest
  username: postgres
before_script:
  - "psql -c 'create database serverMonitorTest;' -U postgres"

script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
services:
 -postgresql

env:
  -NODE_ENV="development"

install:
  - npm install 
  - npm install sequelize
  - npm install -g codecov

notifications: 
  email:
    on_success: never
    on_failure: change