language: node_js

node_js:
  "8.10.0"

services:
 - postgresql

postgres:
  adapter: postgresql
  database: serverMonitorTest
  username: postgres


before_script:
  - psql -c "CREATE DATABASE serverMonitorTest;" -U postgres

script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov


env:
  - NODE_ENV="test"

install:
  - npm install 
  - npm install -g codecov

notifications: 
  email:
    on_success: never
    on_failure: change