language: node_js

node_js:
  "8.10.0"

services:
  - postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install sequelize@$(echo $SEQUELIZE)
script:
  - npm run setupDb
  - npm test
  - npm run coverage


install:
  - npm install 
  - npm install istanbul
  - npm install -g sequelize-cli
  - npm install -g codecov

notifications: 
  email:
    on_success: never
    on_failure: change